name: grabbing streams

on:
  schedule:
    - cron: '0 */1 * * *'  # Εκτελείται κάθε 1 ώρα
  workflow_dispatch:  # Μπορείς να το τρέξεις και χειροκίνητα

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Κάνει clone το repo

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Εγκαθιστά Python 3

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Εγκαθιστά όλες τις εξαρτήσεις από το requirements.txt

      - name: Config git
        run: |
          git config --global user.email "youremail@example.com"
          git config --global user.name "GitHub Actions"

      - name: Grab m3u files (Twitch & Dailymotion)
        run: |
          cd ./core/platforms/
          python3 twitch.py capitalcyp > ../../streams/CAPITAL.m3u8
          # Πρόσθεσε εδώ όλα τα υπόλοιπα Twitch/Dailymotion streams

      - name: Grab anacon streams (PHP)
        run: |
          cd ./core/platforms/
          php save_all_streams.php

      - name: Commit and Push
        run: |
          git add -A
          git commit -m "Streams updated"
          git push
